/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "GrimGuardian"

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://repo.papermc.io/repository/maven-public/")
    }
}
include("main")
include("v1_21_R3")
include("v1_21_R1")
