name: GrimGuardian
version: '${version}'
main: com.gmail.theminiluca.grim.guardian.GrimGuardian
api-version: 1.20
depend:
  - packetevents
  - GrimAC
commands:
  debug:
    permission: grim.debug
    description: module debug tools