name: Build and Release

on:
  push:
    branches:
      - '**'    # 모든 브랜치 커밋 시 빌드 실행
    tags:
      - 'v*'    # 버전 태그 푸시 시 빌드 + 릴리즈 실행

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Release (on tag push only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
